var A = 3;  // create global variable
function Add_number_1() {  // create a function call the global variable.....
    document.write(7 + A); 
}
function Add_number_2() {   // create a function call the global and local variable.....
    var Y = 1;
    document.write(9 + A + Y);
}
function Add_number_3() {   //create a function call the global variable and try to call a local variable from another function.....
    document.write(A + Y);
}
Add_number_1();  // print the return for the first function....
Add_number_2();  //print the return for the second function....
Add_number_3();  //print the return for the third function....
function get_Date() {  // create a function using Get Method
    if (new Date().getHours() < 23) {
    document.getElementById("Greeting").innerHTML= "Hoe are you today?";  // print the return....
    }
}
function Age_Function() {  //create a function using  if and else statment ....
    Age = document.getElementById("Age"). value;
    if (Age >= 18) {  // craete the if condition...
        Vote = "You are old enough to vote!";
    }
    else {  // create the else condition....
        Vote = "You are not old enough to vote!";
    }
    document.getElementById("How_old_are_you?").innerHTML = Vote;   // print the return ...
}
function Time_Function() {   // craete a function using else if statment....
    var Time = new Date().getHours();
    var Replay;
    if(Time < 12 == Time > 0) {  // create if condition...
        Replay = "It is morning time!";
    }
    else if (Time >= 12 == Time < 18) {  // craete else if condition....
        Replay = "It is afternoon.";
    }
    else {  // create else condittion...
        Replay = "It is evening time.";
    }
    document.getElementById("Time_of_day").innerHTML = Replay;   // print the return...
}