function all_vehicles() {  // create new function ...
    var vehicle_1 = " Ford ";  // create new variable...
    var vehicle_2 = " Toyota ";  // create new variable...
    var vehicle_3 = " Audi ";    // create new variable...
    var vehicle_4 = " BMW ";     // create new variable...
    var The_vehicles = vehicle_1.concat(vehicle_2, vehicle_3, vehicle_4);   // create new variable that put all previous variable together using concat Method....
    document.getElementById("Concatenate").innerHTML = The_vehicles;    // print the result using the Concatenate....
}
function slice_Method() {   // create new function .....
    var Sentence = "All work and no play makes Johnny a dull boy.";   // create new variable...
    var Section = Sentence.slice(27,33);  // create a variable using Slice Method to slice previous variable....
    document.getElementById("Slice").innerHTML = Section;  // print the result...
}
function string_Method() { //create new function...
    var X = 182;   // create new variable ....
    document.getElementById("Number_to_string").innerHTML = X.toString();   // using string Method print the result to give it sa string...
}
function precision_Method() {   // create new function...
    var X = 12938.3012987376112;  //create new variable...
    document.getElementById("Precision").innerHTML = X.toPrecision(10);  // using Precision Method print the result ....
}